### PR TITLE
Selenium test dsl interpreter

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
I tweaked hs-webdriver a bit and pointed our repo to the downstream branch.

I'm giving up for today; @andorp if you want to take over be my guest!

**Comment by andorp** [comment]
@fisx: Is there a possibility that the git submodule will not work, please fix it if that happens.

**Comment by fisx** [comment]
`submodules/hs-webdriver` seems fine.  i both checked on my old updated working copy and on a fresh checkout.

**Comment by fisx** [comment]
hum, travis begs to differ...

**Comment by fisx** [comment]
I think i was testing the wrong branch.

what i did for the above commit:

```shell
$ cd submodules
$ git submodule add https://github.com/zerobuzz/hs-webdriver
Adding existing repo at 'submodules/hs-webdriver' to the index
$ git status
On branch 2016-07-26-ap-selenium-test-dsl-interpreter
Your branch is up-to-date with 'origin/2016-07-26-ap-selenium-test-dsl-interpreter'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   submodules/hs-webdriver

Untracked files:
[...]
$ git commit -m 'Fix submodule breakage.'
```

**Comment by fisx** [comment]
cool stuff!

please look at my changes and merge if travis and you are green.

**Comment by andorp** [comment]
LGTM

**Pull request merged**
