### PR TITLE
Display categories in idea list (fixes #498)

### LINKED ISSUE #498: Show idea category in the idea list
- both in wild idea lists and it list of ideas in topic.
- only show icon.
- find a nice place (perhaps next to the author with the same height as the author?

### LINKED ISSUE #499: Add label for category filter
The category filter should have a label with the text “Filtere nach Kategorie“. I’d suggest we put it centered on top of the filters (see edited screenshot for a suggestion)

bildschirmfoto 2016-05-18 um 10 29 06

---
Original Text: Es braucht wohl einen Erklärtext neben dem Kategorienfilter wie "Filtere nach Kategorie:"

### PR DESCRIPTION
**Pull request by np**
Fixes #499, #498, #508.

Tried #519, too, but that's not fixed yet.

### CODE REVIEW

**Comment by localgrr** [comment]
@fisx can you help me move the "durchführbar" and "nicht durchführbar" thing so it's like https://marvelapp.com/ehhb43#10108437 to ideaslist.hs so it's in a position just like ```div_ [class_ "col-2-12 ideas-list-category-container"] $ do``` thanks!

**Comment by fisx** [comment]
NOTE: before we close this, we should go through the issues that it closes and make sure we've covered everything.

**Comment by localgrr** [comment]
OK me done

**Comment by fisx** [comment]
@andorp I would merge this, but I would be more comfortable if you could take a quick look, too.  (I want to clean up the left-over TODOs soon, but elsewhere, unless you want to be consistent...  sorry!  ;-)

**Comment by andorp** [comment]
LGTM

**Pull request merged**
