### PR TITLE
This is the outcome of the post-mortem discussion on the docker issues we had last week.

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
Will write this up soon, then release the PR.

**Comment by fisx** [comment]
@andorp I'm a bit stuck with the TODOs, and hoping that you may have an idea.  Please assign back to me if you want to discuss this.  Thanks!

**Comment by fisx** [comment]
Slightly off-topic: we should also fix the build marker in the aula-docker repo README.  It is still pointing to hub.docker.com.  We could temporarily disable the quay-io build trigger for this push.

**Comment by andorp** [comment]
> Slightly off-topic: we should also fix the build marker in the aula-docker repo README. 

Done. In: https://github.com/liqd/aula-docker/commit/3d4ff0cea385e32cee64ef78c7e90327eb32e422

**Comment by Mikolaj** [comment]
Again, great job. Lessons learned. :)

**Pull request merged**
