### PR TITLE
Configurable avatar path

### PR DESCRIPTION
**Pull request by andorp**

### CODE REVIEW

**Comment by andorp** [comment]
LGTM

**Comment by fisx** [comment]
(please go ahead and merge if you like the last two commits and travis is green.)

**Comment by fisx** [comment]
(*three* commits.  sorry.  :-)

**Comment by andorp** [comment]
LGTM

**Comment by andorp** [comment]
Thanks for the renaming.

**Comment by andorp** [comment]
Fixes: #927

**Pull request merged**
