### PR TITLE
Generics based Arbitrary instances.

### PR DESCRIPTION
**Pull request by andorp**
During the development if we change the structure of our data, we had to adjust the arbitrary instances, which is kind of boilerplate. Usage of generics based arbitrary speeds up the development process.

### CODE REVIEW

**Comment by kosmikus** [comment]
Generally, I'm obviously in favour of using generics. But you're changing current behaviour in a few places, aren't you? In particular where you're replacing code using `arbWord` and `arbPhrase`?

**Comment by andorp** [comment]
@kosmikus You are right, I did two changes unintentionally. I am going to fix them.

**Comment by fisx** [comment]
thanks @kosmikus, all good points!

We just talked about your suggestion to give up on sop and decided against it.  The idea is that we have two kinds of random data: true noise, and consistent system states generated by arbitrary valid user behavior.  The former is what we do in `src/Arbitrary.hs` (which btw will go to `tests/` at some point); the latter will happen in the future.

I just opened related issue #152.

Does that make sense to you?

**Comment by fisx** [comment]
@andorp, could you fix the other comments, wait for #144 to go to master, and then rebase / merge?

thanks!

**Comment by kosmikus** [comment]
@fisx You misunderstand me. I certainly don't advocate to get rid of sop or generics. I say that the two concrete instances which deviate from the generic form should just be given explicitly. Alternatively, introduce a newtype for titles and give it the appropriate `Arbitrary` instance.

**Comment by fisx** [comment]
@kosmikus: ah, ok.  then i just rephrased your suggestion in #152 without noticing?  that means we agree.  good.  (-:

**Comment by fisx** [comment]
LGTM.  Thanks!

**Pull request merged**
