### PR TITLE
Rename `IdeaSpace`s

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by np** [comment]
Work in progress towards #1002

**Comment by np** [comment]
This has only the renaming part but this can be merged.

**Comment by fisx** [comment]
what do you think about this change?:

```
@@ -477,7 +477,7 @@ newtype ClassName = ClassName { _unClassName :: ST }
 -- every school year.)
 data SchoolClass = SchoolClass
     { _classSchoolYear :: Int -- ^ e.g. 2015
-    , _className       :: ST  -- ^ e.g. "7a"
+    , _className       :: ClassName
     }
   deriving (Eq, Ord, Show, Read, Generic)
 
```

**Comment by fisx** [comment]
The following should morally hold, but doesn't technically:

```haskell
fromList [Student (Just c), Student Nothing] === fromList [Student (Just c)]
```

Should we canonicalize this?  Or do you think it's not an issue?  (We should not use equality on role *sets* for authorization checks anyway, I guess.)

**Comment by np** [comment]
@fisx 

Yes `_className :: ClassName` is planned.
I agree that ideally this should hold but I would not bother.

**Comment by fisx** [comment]
@np ack to both answers, thanks.

**Comment by fisx** [comment]
I've played with the styling and moved a validator to module `Frontend.Validation`.  The rest LGTM.  I'll merge when travis is green.

**Comment by fisx** [comment]
thanks!

**Pull request merged**
