### PR TITLE
Get rid of unsafePerformIO in RenderHtml

### PR DESCRIPTION
**Pull request by np**
Only the last commit is part of this PR.

### CODE REVIEW

**Comment by Mikolaj** [comment]
I can't say I understand everything, but the result has definitely an improved readability (and is safer).

BTW, I know it's hard to foresee in advance, but may I ask for a separate commit with style improvements next time? Thank you!

**Comment by andorp** [comment]
LGTM

**Comment by fisx** [comment]
Yes, this is an improvement!

I will add this to #42, where I have touched RenderHtml quite a bit.

**Comment by fisx** [comment]
Manually moved to #42.  Please check and re-open if I missed anything.

**Comment by fisx** [comment]
> BTW, I know it's hard to foresee in advance, but may I ask for a separate commit with style improvements next time? Thank you!

+1

my habit is to work a bit on things, and then commit them in sematic
packages, but not necessarily self-contained.  by allowing for the
latter, it's not that much more work, but the down side is that `git
bisect` won't work any more.  the biggest upside for me is that some
commits can clearly be checked by travis and require almost no human
review at all.

i am in favor of giving up on `git bisect` and aiming for clean,
readable commits.

**Pull request closed without merging**
