### PR TITLE
Refactor Types module

### PR DESCRIPTION
**Pull request by fisx**
Split up `Types` into `Prelude`, `Core`, `Instances.*`, `Util`.  `Core` is still quite big, and because of the cyclical deps I refrained from making type-centered modules (`User`, `Idea`, ...).  But I think it's still an improvement.  I also removed (very few) helper functions.

### CODE REVIEW

**Comment by fisx** [comment]
more or less done, but waiting for #777 to land first.

it would be interesting compare the compile time of 2a61e2f and ded2ce1 in some more controlled setting than travis, too.

**Comment by fisx** [comment]
rebased.

**Comment by fisx** [comment]
A quick test on my machine showed no significant speed-up in compilation time.  I would like to merge the changes anyway for readability.

**Comment by andorp** [comment]
This is a big change, with lot of shuffling, but I have not spotted out any bad change.

**Comment by andorp** [comment]
LGTM

**Pull request merged**
