### PR TITLE
Deriving `Data` for most types

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by np** [comment]
Could we derive the `CoDelegationMap` from the `DelegationMap`?

**Comment by andorp** [comment]
I would use the `setDelegation` functions, generate a list of `(userA, space, userB)` triplet and fold over the list.

**Comment by np** [comment]
@andorp do you think that `gshrink` is correct or is it safer to leave it out.

**Comment by fisx** [comment]
> @andorp do you think that gshrink is correct or is it safer to leave it out.

I guess the time to worry about this more is when we get failing test cases?  :-)

**Comment by fisx** [comment]
LGTM!

I've fixed the `Delegations` shrinking issue after all.  Can be merged when travis agrees.

**Comment by fisx** [comment]
thanks!

**Pull request merged**
