### PR TITLE
Rename from to un in types

### PR DESCRIPTION
**Pull request by andorp**
Fixes: https://github.com/liqd/aula/issues/315

### CODE REVIEW

**Comment by andorp** [comment]
I am not sure if the second commit introduce more readability, feel free to revert.

**Comment by fisx** [comment]
Not sure if there is some morphological rule according to which it sometimes has to be `from` and sometimes `un`, but I like the consistency.

There is also `fromPhase`, `fromProto`.  On the other hand, we won't change `fromList`, `fromMaybe`, `fromEnum`, `fromString`, ...

If nobody has any objections, I'll merge this as is and let #315 close itself.

Thanks!

**Comment by andorp** [comment]
The `fromProto` is differs from the ADT selectors. We are making some other value of a different type with some additional functionality. I would leave it as it is.

**Comment by andorp** [comment]
The `fromPhase` is in a different context, where it indicates a phase transition, in that context the `from` is the valid naming.

**Comment by fisx** [comment]
Oops, I wasn't really thinking.  You're right, merging.

**Pull request merged**
