### PR TITLE
Add Hspec and cabal test suite.

### PR DESCRIPTION
**Pull request by andorp**
Initial commit to start testing with Hspec.

### CODE REVIEW

**Comment by fisx** [comment]
Ah, I see you're still assigned.  Can you merge yourself then?

**Comment by andorp** [comment]
I squashed the commits into one, changed the misleading message.

**Comment by fisx** [comment]
looks good.  you still haven't un-assigned yourself.  is that on purpose?

**Comment by andorp** [comment]
I am going to merge it, as it has the approve from @fisx

**Pull request merged**
