### PR TITLE
Move pages to Page.Comment and Page.Idea

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by fisx** [comment]
@np hlint wants you to use `isNothing` over `== Nothing`.  I guess the motivation is it doesn't require an `Eq` instance, but I don't see a problem with that, and `== Nothing` requires less context, makes things more explicit.  You can either change the code or disable the rule.

**Comment by fisx** [comment]
(or assign to me and i'll do it.)

**Comment by np** [comment]
The argument of context would go away with a prelude module.

**Comment by Mikolaj** [comment]
LGTM.

**Comment by fisx** [comment]
LGTM, too!

**Pull request merged**
