### PR TITLE
Refactor freeze

### LINKED ISSUE #496: Refactor saveAndEnactFreeze
This has been done in 90272b4 in #491, but I'm not convinced that the `assert` is really not necessary.  Therefore, the PR has this commit reverted.

We should add a quickcheck property that replaces it, then cherry-pick this commit and use it in the production .code.  It's much nicer!

### PR DESCRIPTION
**Pull request by fisx**
Fixes #496.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Yes, I think in the current setup, this is dead code. I think `PhaseFreeze` can be removed.

**Comment by fisx** [comment]
Good point!  I'm getting more and more comfortable with this change.  (-:

**Comment by andorp** [comment]
LGTM

**Comment by Mikolaj** [comment]
(lgtm) (forgot to say so long time ago)

**Pull request merged**
