### PR TITLE
Wai metrics

### PR DESCRIPTION
**Pull request by andorp**

### CODE REVIEW

**Comment by fisx** [comment]
cool.

i would like to add an option to not have ekg running.  what would be the best way?  what about making a config sub-type combining host and port, and making the _monitoring entry optional?

i'm happy to do this if you won't have time today, but i'd like to know what you think.

otherwise LGTM.

**Comment by andorp** [comment]
I think it is not a big change.

**Comment by fisx** [comment]
can be merged if you and travis agree.

thanks!

**Comment by andorp** [comment]
LGTM

**Pull request merged**
