### PR TITLE
Add User as a Frame parameter.

### PR DESCRIPTION
**Pull request by andorp**
Preparation, before merging Action monad. The username will come from the session.

### CODE REVIEW

**Comment by andorp** [comment]
@fisx please review

**Comment by fisx** [comment]
Should we just add the entire user, while we are at it?  (The avatar will also be needed, and probably the user id for the link to the profile page.)

(This also conflicts with #42, but I think it will be easy enough to resolve.)

**Comment by fisx** [comment]
(@andorp: i'll hang out on irc for a bit.)

**Comment by fisx** [comment]
I would have preferred two commits here, since I was already finished reading the previous changes.  Also: sorry for making you write `frameUserHack`!  :-)

Otherwise LGTM!  merging~

**Comment by andorp** [comment]
@fisx: let's discuss offline the two commits suggestion. I would like to learn :)

**Comment by andorp** [comment]
> Also: sorry for making you write frameUserHack! :-)

No problem, I just wanted to make it visible for everyone that we should remove it as soon as possible. :)

**Pull request merged**
