### PR TITLE
Use sensei to drive exec/RenderHtml.

### PR DESCRIPTION
**Pull request by fisx**
I just checked: on my laptop, I can set up sensei to watch the repo and on changes in src/Frontend/Page/*.hs, refresh of all html will take <3s.

The only problem is that sensei can't un-watch files.  See https://github.com/hspec/sensei/pull/28 for a discussion what needs to be done there.

### CODE REVIEW

**Comment by np** [comment]
Is tests/RenderHtml.hs a copy of exec/RenderHtml.hs?

**Comment by fisx** [comment]
> Is tests/RenderHtml.hs a copy of exec/RenderHtml.hs?

with small mutations, yes.  probably should have mentioned that.  anyway this is wip, and i'm not sure when i'll get around to do it.  i will keep this assigned to me until it's ready.

**Comment by fisx** [comment]
I did undid some changes and finished some others, and I am quite happy with things now.  Didn't even have to touch sensei.  See commit messages for details.

Possible points of interest:
- the path `/tmp/aula-samples` is hard-wired into `exec/RenderHtml.hs`.  we may want to change that but i'd like to wait for feedback from the users here (i.e., frontend dev)
- @Mikolaj when writing your HOWTO please be aware of the last section in README.md.  It's sloppy writing, so please talk to me if you want me to elaborate, but I think it's close to what you were going to write.

Ready for review (if travis doesn't object, that is).

**Comment by fisx** [comment]
I fixed a problem with sensei in the last 3 commits: despite the symlink, sensei was still triggered by itself and wouldn't stop refreshing.  Now the samples path is read from a shell variable and can be set to anything outside the repo's working copy.

ready for review (this time for real?) -

**Comment by fisx** [comment]
@andorp, assigning this to you, as either you or me will hand this over to frontend dev.

**Comment by fisx** [comment]
will fix merge conflicts.

**Comment by andorp** [comment]
LGTM

**Pull request merged**
