### PR TITLE
Idea lists voting phase

### LINKED ISSUE #507: Show progress bar in list view
The progress bar should indicate yes and no votes in the list view of a topic in the voting phase (topic overview). Currently in v0.11.3 only a grey bar is shown like here: https://thentos-dev-frontend1.liqd.net/space/school/topic/149/ideas

---
Original text from the client: 
In der Liste der Ideen im Thema, wo die Anzahl der Stimmen für jede Idee angezeigt wird, werden nur Stimmen dafür gezählt, Stimmen dagegen nicht angezeigt. Darunter steht die selbe grün-und-graue Leiste, die in der Wilde-Ideen-Phase verwendet wird, wo die dreifarbige Leiste, die auf der Seite der Idee selbst verwendet wird, wohl übersichtlicher und informativer wäre.

### PR DESCRIPTION
**Pull request by fisx**
Fixes #507

### CODE REVIEW

**Comment by fisx** [comment]
2016-05-19-112506_1600x900_scrot

**Comment by fisx** [comment]
(@andorp gave his LGTM off-line, so i'll merge when travis is done.)

**Comment by andorp** [comment]
LGTM online.

**Comment by fisx** [comment]
(-:  thanks!

**Comment by rittermo** [comment]
@fisx Now that we have the full featured voting bar in the idea list, we could maybe remove the thumbs up/down icons in brackets after the vote count, since it only duplicates information? 

bildschirmfoto 2016-05-21 um 12 52 53

**Comment by fisx** [comment]
It's easy to remove, but I added it on purpose: I think the number of voices in "1 Stimme" is unclear: is it yes votes?  or total votes?  total number of people who are allowed to vote?  Let's move this discussion to #506.

**Pull request merged**
