### PR TITLE
Flip delegation tab names on the user profile page.

### PR DESCRIPTION
**Pull request by andorp**
Fixes: #991

### CODE REVIEW

**Comment by fisx** [comment]
LGTM!  can be merged when travis is green.

**Comment by fisx** [comment]
(i wouldn't have added the explanation in two different places for fear of diverging changes, but on second thoughts, the fact that it's easier to find may outweigh this hypothetical problem.)

**Comment by fisx** [comment]
thanks!

**Comment by andorp** [comment]
> (i wouldn't have added the explanation in two different places for fear of diverging changes, but on second thoughts, the fact that it's easier to find may outweigh this hypothetical problem.)

I thought those are the two occurences, even it would be better to use the `Delegate` and `Delegatee` newtype everywhere where it applies, but that would be a bigger change.

**Pull request merged**
