### PR TITLE
Handle removing school classes (issue #1002 part 2)

### PR DESCRIPTION
**Pull request by np**

### CODE REVIEW

**Comment by np** [comment]
Rebased. This still needs a bit more testing.

**Comment by np** [comment]
Rebased again with a better merge resolution.

**Comment by np** [comment]
`AdminDeleteClass` is POST only, the test suite can catch it but it didn't show up until now.

**Comment by np** [comment]
Rebased.

**Comment by np** [comment]
This is ready for you @fisx for styling translation and making a final test.

**Comment by fisx** [comment]
Tested and LGTM.  Will merge when travis agrees.  Thanks!

**Pull request merged**
